---
###
# Author: Justin Quijano
# Description: Playbook to create VM's in vSphere
#
####

  - name: Create Virtual Machine
    vmware.vmware_rest.vcenter_vm:
      placement:
        cluster: "{{ lookup('vmware.vmware_rest.cluster_moid', '/hydrohomie/host/hm_cluster') }}"